import { Day, AppState } from './types';

export const DAYS = [Day.Monday, Day.Tuesday, Day.Wednesday, Day.Thursday, Day.Friday];

export const SLOTS = [
  { id: 's1', time: '09:00 AM - 10:00 AM' },
  { id: 's2', time: '10:00 AM - 11:00 AM' },
  { id: 's3', time: '11:00 AM - 12:00 PM' },
  { id: 's4', time: '12:00 PM - 01:00 PM' },
  { id: 's5', time: '01:00 PM - 02:00 PM' },
];

export const MOCK_STATE: AppState = {
  semesters: [
    { id: 'bca1', name: 'BCA 1' },
    { id: 'bca3', name: 'BCA 3' },
    { id: 'bca5', name: 'BCA 5' },
  ],
  sections: [
    { id: 'sec-b1a', name: 'A', semesterId: 'bca1' },
    { id: 'sec-b1b', name: 'B', semesterId: 'bca1' },
    { id: 'sec-b1c', name: 'C', semesterId: 'bca1' },
    { id: 'sec-b1d', name: 'D', semesterId: 'bca1' },
    { id: 'sec-b3a', name: 'A', semesterId: 'bca3' },
    { id: 'sec-b3b', name: 'B', semesterId: 'bca3' },
    { id: 'sec-b3c', name: 'C', semesterId: 'bca3' },
    { id: 'sec-b3d', name: 'D', semesterId: 'bca3' },
    { id: 'sec-b3e', name: 'E', semesterId: 'bca3' },
    { id: 'sec-b5a', name: 'A', semesterId: 'bca5' },
    { id: 'sec-b5b', name: 'B', semesterId: 'bca5' },
    { id: 'sec-b5c', name: 'C', semesterId: 'bca5' },
    { id: 'sec-b5d', name: 'D', semesterId: 'bca5' },
  ],
  faculty: [
    { id: 'f1', name: 'DR. ABHISHEK MISHRA', subjects: [], department: 'CS', status: 'Present', workloadLimit: 18 },
    { id: 'f2', name: 'DR. MANISHA CHAUDHRY', subjects: [], department: 'CS', status: 'Present', workloadLimit: 18 },
    { id: 'f3', name: 'MS. SHIKHA TIWARI', subjects: [], department: 'CS', status: 'Present', workloadLimit: 18 },
    { id: 'f4', name: 'MS. NEERU SAXENA', subjects: [], department: 'CS', status: 'Present', workloadLimit: 18 },
    { id: 'f5', name: 'DR. PREETIBALA TRIPATHI', subjects: [], department: 'CS', status: 'Present', workloadLimit: 18 },
    { id: 'f6', name: 'MR. ASHISH BHATNAGAR', subjects: [], department: 'CS', status: 'Present', workloadLimit: 18 },
    { id: 'f7', name: 'MS. SHAILZA SHARMA', subjects: [], department: 'CS', status: 'Present', workloadLimit: 18 },
    { id: 'f8', name: 'DR. INDRA PRIYADARSHANI', subjects: [], department: 'CS', status: 'Present', workloadLimit: 18 },
    { id: 'f9', name: 'MS. AKANSHA TYAGI', subjects: [], department: 'CS', status: 'Present', workloadLimit: 18 },
    { id: 'f10', name: 'MS. RICHA BHARDWAJ', subjects: [], department: 'CS', status: 'Present', workloadLimit: 18 },
    { id: 'f11', name: 'MS. RASHMI SINGH', subjects: [], department: 'CS', status: 'Present', workloadLimit: 18 },
    { id: 'f12', name: 'MS. YASHDA SINGH', subjects: [], department: 'CS', status: 'Present', workloadLimit: 18 },
    { id: 'f13', name: 'MS. PURNIMA GUPTA', subjects: [], department: 'CS', status: 'Present', workloadLimit: 18 },
    { id: 'f14', name: 'DR. NIKITA JOSHI MISHRA', subjects: [], department: 'CS', status: 'Present', workloadLimit: 18 },
    { id: 'f15', name: 'MR. SURYA SAXENA', subjects: [], department: 'CS', status: 'Present', workloadLimit: 18 },
    { id: 'f16', name: 'MS. ARCHANA GUPTA', subjects: [], department: 'CS', status: 'Present', workloadLimit: 18 },
    { id: 'f17', name: 'MS. SWATI RAWAT', subjects: [], department: 'CS', status: 'Present', workloadLimit: 18 },
    { id: 'f18', name: 'MR. ROHIET JAIN', subjects: [], department: 'CS', status: 'Present', workloadLimit: 18 },
    { id: 'f19', name: 'MR. SUNIL KUMAR SHARMA', subjects: [], department: 'CS', status: 'Present', workloadLimit: 18 },
    { id: 'f20', name: 'DR. GAGAN VARSHNEY', subjects: [], department: 'CS', status: 'Present', workloadLimit: 18 },
    { id: 'f21', name: 'MR. GAURAV KAUSHIK', subjects: [], department: 'CS', status: 'Present', workloadLimit: 18 },
    { id: 'f22', name: 'DR. SANDEEP SHARMA', subjects: [], department: 'CS', status: 'Present', workloadLimit: 18 },
    { id: 'f23', name: 'DR. ASHUTOSH SHARMA', subjects: [], department: 'CS', status: 'Present', workloadLimit: 18 },
    { id: 'f24', name: 'MS. RASHMI VAISHNAV', subjects: [], department: 'CS', status: 'Present', workloadLimit: 18 },
    { id: 'f25', name: 'MS. SUSHMA JHA', subjects: [], department: 'CS', status: 'Present', workloadLimit: 18 },
  ],
  subjects: [
    { id: 's-m1', name: 'MATHS-I', code: 'BCA101', weeklyFrequency: 4 },
    { id: 's-ppa', name: 'PPA', code: 'BCA102', weeklyFrequency: 5 },
    { id: 's-cfoa', name: 'CFOA', code: 'BCA103', weeklyFrequency: 5 },
    { id: 's-pom', name: 'POM', code: 'BCA104', weeklyFrequency: 3 },
    { id: 's-bc', name: 'BC', code: 'BCA105', weeklyFrequency: 3 },
    { id: 's-evs', name: 'EVS', code: 'BCA106', weeklyFrequency: 2 },
    { id: 's-cpp', name: 'C++', code: 'BCA301', weeklyFrequency: 5 },
    { id: 's-dsc', name: 'DSC', code: 'BCA302', weeklyFrequency: 5 },
    { id: 's-caal', name: 'CAAL', code: 'BCA303', weeklyFrequency: 4 },
    { id: 's-eco', name: 'ECO', code: 'BCA304', weeklyFrequency: 4 },
    { id: 's-stats', name: 'STATS', code: 'BCA305', weeklyFrequency: 4 },
    { id: 's-dbms', name: 'DBMS', code: 'BCA501', weeklyFrequency: 5 },
    { id: 's-java', name: 'JAVA', code: 'BCA502', weeklyFrequency: 5 },
    { id: 's-cn', name: 'CN', code: 'BCA503', weeklyFrequency: 4 },
    { id: 's-nm', name: 'NM', code: 'BCA504', weeklyFrequency: 3 },
    { id: 's-lms', name: 'LMS', code: 'BCA505', weeklyFrequency: 1 },
  ],
  assignments: [
    // BCA 1
    { id: 'a1', sectionId: 'sec-b1a', subjectId: 's-m1', facultyId: 'f1' },
    { id: 'a2', sectionId: 'sec-b1b', subjectId: 's-m1', facultyId: 'f1' },
    { id: 'a3', sectionId: 'sec-b1c', subjectId: 's-m1', facultyId: 'f1' },
    { id: 'a4', sectionId: 'sec-b1d', subjectId: 's-m1', facultyId: 'f2' },
    { id: 'a5', sectionId: 'sec-b1a', subjectId: 's-ppa', facultyId: 'f3' },
    { id: 'a6', sectionId: 'sec-b1b', subjectId: 's-ppa', facultyId: 'f4' },
    { id: 'a7', sectionId: 'sec-b1c', subjectId: 's-ppa', facultyId: 'f4' },
    { id: 'a8', sectionId: 'sec-b1d', subjectId: 's-ppa', facultyId: 'f4' },
    { id: 'a9', sectionId: 'sec-b1a', subjectId: 's-cfoa', facultyId: 'f5' },
    { id: 'a10', sectionId: 'sec-b1b', subjectId: 's-cfoa', facultyId: 'f5' },
    { id: 'a11', sectionId: 'sec-b1c', subjectId: 's-cfoa', facultyId: 'f6' },
    { id: 'a12', sectionId: 'sec-b1d', subjectId: 's-cfoa', facultyId: 'f7' },
    { id: 'a13', sectionId: 'sec-b1a', subjectId: 's-pom', facultyId: 'f8' },
    { id: 'a14', sectionId: 'sec-b1b', subjectId: 's-pom', facultyId: 'f9' },
    { id: 'a15', sectionId: 'sec-b1c', subjectId: 's-pom', facultyId: 'f10' },
    { id: 'a16', sectionId: 'sec-b1d', subjectId: 's-pom', facultyId: 'f10' },
    { id: 'a17', sectionId: 'sec-b1a', subjectId: 's-bc', facultyId: 'f11' },
    { id: 'a18', sectionId: 'sec-b1b', subjectId: 's-bc', facultyId: 'f11' },
    { id: 'a19', sectionId: 'sec-b1c', subjectId: 's-bc', facultyId: 'f11' },
    { id: 'a20', sectionId: 'sec-b1d', subjectId: 's-bc', facultyId: 'f11' },
    { id: 'a21', sectionId: 'sec-b1a', subjectId: 's-evs', facultyId: 'f12' },
    { id: 'a22', sectionId: 'sec-b1b', subjectId: 's-evs', facultyId: 'f12' },
    { id: 'a23', sectionId: 'sec-b1c', subjectId: 's-evs', facultyId: 'f12' },
    { id: 'a24', sectionId: 'sec-b1d', subjectId: 's-evs', facultyId: 'f12' },
    // BCA 3
    { id: 'a25', sectionId: 'sec-b3a', subjectId: 's-cpp', facultyId: 'f13' },
    { id: 'a26', sectionId: 'sec-b3b', subjectId: 's-cpp', facultyId: 'f13' },
    { id: 'a27', sectionId: 'sec-b3c', subjectId: 's-cpp', facultyId: 'f14' },
    { id: 'a28', sectionId: 'sec-b3d', subjectId: 's-cpp', facultyId: 'f14' },
    { id: 'a29', sectionId: 'sec-b3e', subjectId: 's-cpp', facultyId: 'f5' },
    { id: 'a30', sectionId: 'sec-b3a', subjectId: 's-dsc', facultyId: 'f15' },
    { id: 'a31', sectionId: 'sec-b3b', subjectId: 's-dsc', facultyId: 'f15' },
    { id: 'a32', sectionId: 'sec-b3c', subjectId: 's-dsc', facultyId: 'f15' },
    { id: 'a33', sectionId: 'sec-b3d', subjectId: 's-dsc', facultyId: 'f6' },
    { id: 'a34', sectionId: 'sec-b3e', subjectId: 's-dsc', facultyId: 'f6' },
    { id: 'a35', sectionId: 'sec-b3a', subjectId: 's-caal', facultyId: 'f16' },
    { id: 'a36', sectionId: 'sec-b3b', subjectId: 's-caal', facultyId: 'f16' },
    { id: 'a37', sectionId: 'sec-b3c', subjectId: 's-caal', facultyId: 'f16' },
    { id: 'a38', sectionId: 'sec-b3d', subjectId: 's-caal', facultyId: 'f3' },
    { id: 'a39', sectionId: 'sec-b3e', subjectId: 's-caal', facultyId: 'f3' },
    { id: 'a40', sectionId: 'sec-b3a', subjectId: 's-eco', facultyId: 'f17' },
    { id: 'a41', sectionId: 'sec-b3b', subjectId: 's-eco', facultyId: 'f17' },
    { id: 'a42', sectionId: 'sec-b3c', subjectId: 's-eco', facultyId: 'f17' },
    { id: 'a43', sectionId: 'sec-b3d', subjectId: 's-eco', facultyId: 'f18' },
    { id: 'a44', sectionId: 'sec-b3e', subjectId: 's-eco', facultyId: 'f18' },
    { id: 'a45', sectionId: 'sec-b3a', subjectId: 's-stats', facultyId: 'f2' },
    { id: 'a46', sectionId: 'sec-b3b', subjectId: 's-stats', facultyId: 'f2' },
    { id: 'a47', sectionId: 'sec-b3c', subjectId: 's-stats', facultyId: 'f2' },
    { id: 'a48', sectionId: 'sec-b3d', subjectId: 's-stats', facultyId: 'f19' },
    { id: 'a49', sectionId: 'sec-b3e', subjectId: 's-stats', facultyId: 'f19' },
    // BCA 5
    { id: 'a50', sectionId: 'sec-b5a', subjectId: 's-dbms', facultyId: 'f20' },
    { id: 'a51', sectionId: 'sec-b5b', subjectId: 's-dbms', facultyId: 'f20' },
    { id: 'a52', sectionId: 'sec-b5c', subjectId: 's-dbms', facultyId: 'f21' },
    { id: 'a53', sectionId: 'sec-b5d', subjectId: 's-dbms', facultyId: 'f14' },
    { id: 'a54', sectionId: 'sec-b5a', subjectId: 's-java', facultyId: 'f13' },
    { id: 'a55', sectionId: 'sec-b5b', subjectId: 's-java', facultyId: 'f22' },
    { id: 'a56', sectionId: 'sec-b5c', subjectId: 's-java', facultyId: 'f22' },
    { id: 'a57', sectionId: 'sec-b5d', subjectId: 's-java', facultyId: 'f22' },
    { id: 'a58', sectionId: 'sec-b5c', subjectId: 's-cn', facultyId: 'f23' },
    { id: 'a59', sectionId: 'sec-b5a', subjectId: 's-cn', facultyId: 'f16' },
    { id: 'a60', sectionId: 'sec-b5b', subjectId: 's-cn', facultyId: 'f16' },
    { id: 'a61', sectionId: 'sec-b5d', subjectId: 's-cn', facultyId: 'f16' },
    { id: 'a62', sectionId: 'sec-b5a', subjectId: 's-nm', facultyId: 'f24' },
    { id: 'a63', sectionId: 'sec-b5b', subjectId: 's-nm', facultyId: 'f24' },
    { id: 'a64', sectionId: 'sec-b5c', subjectId: 's-nm', facultyId: 'f24' },
    { id: 'a65', sectionId: 'sec-b5d', subjectId: 's-nm', facultyId: 'f24' },
    { id: 'a66', sectionId: 'sec-b5a', subjectId: 's-lms', facultyId: 'f25' },
    { id: 'a67', sectionId: 'sec-b5b', subjectId: 's-lms', facultyId: 'f25' },
    { id: 'a68', sectionId: 'sec-b5c', subjectId: 's-lms', facultyId: 'f25' },
    { id: 'a69', sectionId: 'sec-b5d', subjectId: 's-lms', facultyId: 'f25' },
  ],
  masterTimetable: [],
  dailyAdjustments: {},
  facultyAvailability: {},
  events: [],
  config: {
    totalSlots: 5
  }
};